DROP TABLE TRANSACTIONS IF EXISTS;

CREATE TABLE TRANSACTIONS
(
	"ID" INTEGER AUTO_INCREMENT PRIMARY KEY,
	"TYPE" VARCHAR(31),
	"QUANTITY" INTEGER,
	"PRICE" DOUBLE,
	"CLIENT_ID" VARCHAR(31),
	"EXECUTION_DATE" DATE,
	"SETTLEMENT_DATE" DATE
);